title: The HPC PowerStack 
subtitle:  A Path to Standardization and/or Homogenization?
#description: June 20 to June 22, 2018, TUM Akademiezentrum Raitenhaslach, Germany
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
